// Generated by CoffeeScript 1.4.0

define(["jquery", "controller/loading", "view/loading", "controller/screen1", "view/screen1"], function($, LoadingController, LoadingView, screen1Controller, screen1View) {
  var Core;
  return Core = (function() {

    function Core() {}

    Core.prototype.init = function() {
      var _this = this;
      this.LoadingController = new LoadingController();
      this.LoadingController.setView(new LoadingView($("#loading")));
      this.LoadingController.activate();
      this.screen1Controller = new screen1Controller();
      this.screen1Controller.setView(new screen1View($("#main")));
      this.screen1Controller.deactivate();
      return $('body').bind('keypress', function(e) {
        return _this.dispatch(e.which);
      });
    };

    Core.prototype.dispatch = function(e) {
      return console.log("dispatched " + e);
    };

    return Core;

  })();
});
