// Generated by CoffeeScript 1.4.0

define(["jquery"], function($) {
  var LoadingView;
  return LoadingView = (function() {

    function LoadingView(jqueryDivSelected) {
      this.jqueryDivSelected = jqueryDivSelected;
      console.log('construct LoadingView');
    }

    LoadingView.prototype.show = function() {
      return this.jqueryDivSelected.show();
    };

    LoadingView.prototype.hide = function() {
      return this.jqueryDivSelected.hide();
    };

    return LoadingView;

  })();
});
