// Generated by CoffeeScript 1.4.0

define(["jquery"], function($) {
  var Screen1View;
  return Screen1View = (function() {

    function Screen1View(jqueryDivSelected) {
      this.jqueryDivSelected = jqueryDivSelected;
      console.log('construct LoadingView');
    }

    Screen1View.prototype.show = function() {
      return this.jqueryDivSelected.show();
    };

    Screen1View.prototype.hide = function() {
      return this.jqueryDivSelected.hide();
    };

    return Screen1View;

  })();
});
